/** @type import("svgo").Config */
export default {
  multipass: true,
  floatPrecision: 8,
  plugins: [
    "cleanupAttrs",
    "cleanupEnableBackground",
    "cleanupIds",
    // "cleanupListOfValues",
    "cleanupNumericValues",
    "collapseGroups",
    "convertColors",
    "convertEllipseToCircle",
    "convertOneStopGradients",
    "convertPathData",
    "convertShapeToPath",
    "convertStyleToAttrs",
    "convertTransform",
    "inlineStyles",
    "mergePaths",
    "mergeStyles",
    "minifyStyles",
    "moveElemsAttrsToGroup",
    "moveGroupAttrsToElems",
    // "prefixIds",
    "removeComments",
    "removeDesc",
    "removeDimensions",
    "removeDoctype",
    "removeEditorsNSData",
    "removeEmptyAttrs",
    "removeEmptyContainers",
    "removeEmptyText",
    "removeHiddenElems",
    "removeMetadata",
    "removeNonInheritableGroupAttrs",
    "removeOffCanvasPaths",
    // "removeRasterImages",
    // "removeScriptElement",
    // "removeStyleElement",
    "removeTitle",
    "removeUnknownsAndDefaults",
    "removeUnusedNS",
    "removeUselessDefs",
    "removeUselessStrokeAndFill",
    // "removeViewBox",
    // "removeXMLNS",
    "removeXMLProcInst",
    "removeXlink",
    "reusePaths",
    "sortAttrs",
    "sortDefsChildren",
  ],
};
